import api from './axios'

export const getAdminStatsApi = () => api.get('/admin/stats')
export const getAdminCoursesApi = () => api.get('/admin/courses')
export const createAdminCourseApi = (payload) => api.post('/admin/courses', payload)
export const updateAdminCourseApi = (id, payload) => api.put(`/admin/courses/${id}`, payload)
export const toggleAdminCourseApi = (id) => api.patch(`/admin/courses/${id}/toggle`)

export const getAdminQuizzesApi = () => api.get('/admin/quizzes')
export const getAdminQuizzesWithFilterApi = (params) => api.get('/admin/quizzes', { params })
export const createAdminQuizApi = (payload) => api.post('/admin/quizzes', payload)
export const getAdminQuizApi = (id) => api.get(`/admin/quizzes/${id}`)
export const updateAdminQuizApi = (id, payload) => api.put(`/admin/quizzes/${id}`, payload)
export const deleteAdminQuizApi = (id) => api.delete(`/admin/quizzes/${id}`)
export const toggleAdminQuizApi = (id) => api.patch(`/admin/quizzes/${id}/toggle`)

export const getAdminQuizQuestionsApi = (quizId) => api.get(`/admin/quizzes/${quizId}/questions`)
export const createAdminQuizQuestionApi = (quizId, payload) => api.post(`/admin/quizzes/${quizId}/questions`, payload)
export const updateAdminQuestionApi = (id, payload) => api.put(`/admin/questions/${id}`, payload)
export const updateAdminQuestionFormApi = (id, payload) => api.post(`/admin/questions/${id}`, payload)
export const deleteAdminQuestionApi = (id) => api.delete(`/admin/questions/${id}`)
export const reorderAdminQuizQuestionsApi = (quizId, payload) => api.patch(`/admin/quizzes/${quizId}/questions/reorder`, payload)

export const getAdminIdeProblemsApi = () => api.get('/admin/ide-problems')
export const createAdminIdeProblemApi = (payload) => api.post('/admin/ide-problems', payload)
export const getAdminIdeProblemApi = (id) => api.get(`/admin/ide-problems/${id}`)
export const updateAdminIdeProblemApi = (id, payload) => api.put(`/admin/ide-problems/${id}`, payload)
export const deleteAdminIdeProblemApi = (id) => api.delete(`/admin/ide-problems/${id}`)
export const addAdminIdeTestCaseApi = (id, payload) => api.post(`/admin/ide-problems/${id}/test-cases`, payload)
export const updateAdminIdeTestCaseApi = (id, payload) => api.put(`/admin/test-cases/${id}`, payload)
export const deleteAdminIdeTestCaseApi = (id) => api.delete(`/admin/test-cases/${id}`)
